defmodule IdeajarWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ideajar

  # Session cookie configuration (signed cookie store, HttpOnly, SameSite=Lax,
  # 10-year Max-Age, Secure in :prod). Resolved at compile time from
  # `:session_options` app env so each Mix env contributes its own hardening.
  @session_options Application.compile_env!(:ideajar, :session_options)

  @doc """
  Returns the session options used by `Plug.Session` and the LiveView socket.
  Exposed for tests that need to verify hardening attributes.
  """
  def session_options, do: @session_options

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ideajar,
    gzip: not code_reloading?,
    only: IdeajarWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ideajar
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug IdeajarWeb.Router
end
